import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Noto_Sans_SC,
  Noto_Sans_TC,
} from "next/font/google";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { getLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import MainLayout from "@/components/main-layout";
import Providers from "@/components/providers";
import { cn } from "@/utils/cn";
import type { Viewport } from "next";

// export const viewport: Viewport = {
//   themeColor: [
//     { media: "(prefers-color-scheme: light)", color: "white" },
//     { media: "(prefers-color-scheme: dark)", color: "black" },
//   ],
// };

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const notoSansTC = Noto_Sans_TC({
  variable: "--font-noto-sans-tc",
  subsets: ["latin"],
  display: "swap",
});

const notoSansSC = Noto_Sans_SC({
  variable: "--font-noto-sans-sc",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  return (
    <html
      lang={locale}
      className={cn(
        geistSans.variable,
        geistMono.variable,
        notoSansTC.variable,
        notoSansSC.variable
      )}
      data-scroll-behavior="smooth"
      suppressHydrationWarning
    >
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body> */}
      <body className="relative flex min-h-screen flex-col">
        <Providers>
          <NextIntlClientProvider>
            {<MainLayout>{children}</MainLayout>}
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}
